[package]
name = "ducks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
human_bytes = "0.4.1"

[[bin]]
name = "ducks"
path = "ducks.rs"
